In [1]:
import numpy as np
import pandas as pd

In [2]:
def process_data(data, poids):
    nb_candidats = len(data)
    comparaison_matrice = np.zeros((nb_candidats, nb_candidats))

    # Compare les candidats deux à deux en conservant les poids pertinents
    for i in range(nb_candidats):
        for j in range(nb_candidats):
            if i != j:
                for k in range(len(poids)):
                    if data.iloc[i, k] >= data.iloc[j, k]:
                        comparaison_matrice[i, j] += poids[k]

    print("Matrice de comparaison des candidats :")
    print(comparaison_matrice)

    flux_positif = comparaison_matrice.sum(axis=0)
    flux_negatif = comparaison_matrice.sum(axis=1)

    # Récupérer les noms des candidats à partir des premières valeurs de chaque ligne
    candidat_names = [data.iloc[i, 0] for i in range(nb_candidats)]

    flux_dict_po = {candidat_names[i]: flux for i, flux in enumerate(flux_positif)}
    print("Dictionnaire des valeurs de flux associées aux candidats (Flux Positif):")
    print(flux_dict_po)

    flux_dict_neg = {candidat_names[i]: flux for i, flux in enumerate(flux_negatif)}
    print("Dictionnaire des valeurs de flux associées aux candidats (Flux Négatif):")
    print(flux_dict_neg)

    sorted_candidats_po = sorted(flux_dict_po, key=lambda candidat: flux_dict_po[candidat], reverse=True)
    print("Ordre des candidats en fonction des valeurs de flux positif (ordre décroissant):")
    for i, candidat in enumerate(sorted_candidats_po, start=1):
        print(f"Position {i}: {candidat}")

    sorted_candidats_neg = sorted(flux_dict_neg, key=lambda candidat: flux_dict_neg[candidat])
    print("Ordre des candidats en fonction des valeurs de flux négatif (ordre croissant):")
    for i, candidat in enumerate(sorted_candidats_neg, start=1):
        print(f"Position {i}: {candidat}")


In [3]:
col_names = ['candidat','g1','g2','g3','g4','g5','g6','g7'] 
data = data_voiture = pd.read_csv('data/donnees.csv', names=col_names)

In [4]:
data

candidat     g1   g2   g3    g4  g5   g6    g7
0       V1  23817  201  8.0  39.6   6  378  31.2
1       V2  25771  195  5.7  35.8   7  440  33.0
2       V3  25496  195  7.9  37.0   2  480  34.0
3       V4  25649  191  8.3  34.4   2  430  34.6
4       V5  26183  199  7.8  35.7   5  494  32.0
5       V6  23664  194  7.7  37.4   4  452  33.8
6       V7  23344  195  7.6  34.4   3  475  33.6
7       V8  26260  209  6.6  36.6   4  440  30.9
8       V9  19084  182  6.4  40.6   8  408  33.5
9      V10  29160  203  7.5  34.5   1  520  32.0

In [5]:
poids = [0.2, 0.1, 0.15, 0.15, 0.1, 0.1, 0.2]

In [6]:
process_data(data, poids)

Matrice de comparaison des candidats :
[[0.   0.4  0.5  0.35 0.5  0.6  0.6  0.35 0.4  0.35]
 [0.6  0.   0.35 0.65 0.2  0.35 0.45 0.3  0.45 0.4 ]
 [0.5  0.8  0.   0.55 0.25 0.6  0.7  0.45 0.6  0.55]
 [0.65 0.35 0.55 0.   0.15 0.25 0.35 0.15 0.6  0.45]
 [0.5  0.8  0.75 0.85 0.   0.7  0.8  0.45 0.6  0.55]
 [0.4  0.65 0.4  0.75 0.3  0.   0.45 0.55 0.6  0.55]
 [0.4  0.7  0.45 0.75 0.2  0.55 0.   0.35 0.6  0.45]
 [0.65 0.9  0.55 0.85 0.55 0.55 0.65 0.   0.6  0.55]
 [0.6  0.55 0.4  0.4  0.4  0.4  0.4  0.4  0.   0.4 ]
 [0.65 0.6  0.45 0.55 0.45 0.45 0.55 0.45 0.6  0.  ]]
Dictionnaire des valeurs de flux associées aux candidats (Flux Positif):
{'V1': 4.950000000000001, 'V2': 5.75, 'V3': 4.3999999999999995, 'V4': 5.7, 'V5': 3.0, 'V6': 4.449999999999999, 'V7': 4.949999999999999, 'V8': 3.45, 'V9': 5.050000000000001, 'V10': 4.25}
Dictionnaire des valeurs de flux associées aux candidats (Flux Négatif):
{'V1': 4.05, 'V2': 3.7500000000000004, 'V3': 5.0, 'V4': 3.5, 'V5': 6.000000000000001, 'V6': 4.6499